#!/bin/sh

if which docker-compose; then
        COMPOSE='docker-compose'
else
        COMPOSE='docker compose'
fi

set -e

$COMPOSE -f docker-compose-test.yml up --force-recreate -d

echo 'GET / HTTP/1.0

'|nc localhost 3000|grep 'Hello World' && echo OK

$COMPOSE -f docker-compose-test.yml down
